# Generated by Django 5.2.3 on 2025-06-23 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notebooks", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="report",
            name="paper_content",
        ),
        migrations.RemoveField(
            model_name="report",
            name="transcript_content",
        ),
        migrations.AddField(
            model_name="report",
            name="csv_date_filter",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="report",
            name="csv_session_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="report",
            name="do_generate_article",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="do_generate_outline",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="do_polish_article",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="do_research",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="domain_list",
            field=models.JSONField(
                blank=True, default=list, help_text="Whitelist domains"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="final_context_k",
            field=models.PositiveIntegerField(
                default=20, help_text="Final context K (10-100)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="generated_files",
            field=models.JSONField(
                blank=True, default=list, help_text="List of generated file paths"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="include_domains",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="initial_retrieval_k",
            field=models.PositiveIntegerField(
                default=150, help_text="Initial retrieval K (50-500)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="job_id",
            field=models.CharField(
                blank=True,
                help_text="Background job ID for tracking",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="main_report_file",
            field=models.FileField(
                blank=True, upload_to='reports/'
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="max_perspective",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum perspectives (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="max_thread_num",
            field=models.PositiveIntegerField(
                default=10, help_text="Maximum threads (1-20)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="post_processing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="processing_logs",
            field=models.JSONField(
                blank=True, default=list, help_text="Processing log messages"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="progress",
            field=models.CharField(
                blank=True, help_text="Current progress message", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="prompt_type",
            field=models.CharField(
                choices=[("general", "General"), ("financial", "Financial")],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="remove_duplicate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="reranker_threshold",
            field=models.FloatField(
                default=0.5, help_text="Reranker threshold (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="result_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional result metadata"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="search_depth",
            field=models.CharField(
                choices=[("basic", "Basic"), ("advanced", "Advanced")],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="search_top_k",
            field=models.PositiveIntegerField(
                default=10, help_text="Top K search results (5-50)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="selected_file_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of file IDs from knowledge base",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="selected_url_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of URL IDs from knowledge base",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="skip_rewrite_outline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="time_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                    ("year", "Year"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="max_conv_turn",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum conversation turns (1-10)"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="model_provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("google", "Google")],
                default="openai",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="result_content",
            field=models.TextField(blank=True, help_text="Generated report content"),
        ),
        migrations.AlterField(
            model_name="report",
            name="retriever",
            field=models.CharField(
                choices=[
                    ("tavily", "Tavily"),
                    ("brave", "Brave"),
                    ("serper", "Serper"),
                    ("you", "You"),
                    ("bing", "Bing"),
                    ("duckduckgo", "DuckDuckGo"),
                    ("searxng", "SearXNG"),
                    ("azure_ai_search", "Azure AI Search"),
                ],
                default="tavily",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="temperature",
            field=models.FloatField(
                default=0.2, help_text="Temperature for LLM generation (0.0-2.0)"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="top_p",
            field=models.FloatField(
                default=0.4, help_text="Top-p for LLM generation (0.0-1.0)"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="topic",
            field=models.CharField(
                blank=True, help_text="Research topic", max_length=500
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["user", "status"], name="reports_rep_user_id_8456e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["job_id"], name="reports_rep_job_id_4b74e3_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_at"], name="reports_rep_created_a6aabf_idx"
            ),
        ),
    ]
