# Generated by Django 5.2.3 on 2025-07-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'status'], name='reports_rep_user_id_8456e4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['job_id'], name='reports_rep_job_id_4b74e3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['storage_uuid'], name='reports_rep_storage_d31fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['main_report_object_key'], name='reports_rep_main_re_462cd9_idx'),
        ),
    ]
