# Generated by Django 5.2.3 on 2025-07-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_storage_d31fdd_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='storage_uuid',
        ),
    ]
