# Generated by Django 5.2.3 on 2025-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_add_old_outline_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="selected_file_ids",
        ),
        migrations.RemoveField(
            model_name="report",
            name="selected_url_ids",
        ),
        migrations.AddField(
            model_name="report",
            name="selected_files_paths",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of file folder paths from knowledge base",
            ),
        ),
    ]
