# Generated by Django 5.2.3 on 2025-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_refactor_file_selection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
