# Generated by Django 5.2.3 on 2025-07-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_result_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('figure_id', models.UUIDField(editable=False, help_text='Unique figure identifier from knowledge base', primary_key=True, serialize=False)),
                ('image_caption', models.TextField(blank=True, help_text='Description or caption for the image')),
                ('minio_object_key', models.CharField(db_index=True, help_text='MinIO object key for the image file in report folder', max_length=255)),
                ('image_metadata', models.JSONField(default=dict, help_text='Image metadata including dimensions, format, size, etc.')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the image (image/png, image/jpeg, etc.)', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('source_minio_object_key', models.CharField(blank=True, help_text='Original MinIO object key from knowledge base', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(help_text='Report this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Image',
                'verbose_name_plural': 'Report Images',
                'ordering': ['report', 'created_at'],
                'indexes': [models.Index(fields=['report', 'created_at'], name='reports_rep_report__0056c2_idx'), models.Index(fields=['minio_object_key'], name='reports_rep_minio_o_383b08_idx')],
            },
        ),
    ]
