# Generated by Django 5.2.3 on 2025-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='figure_data_path',
            field=models.CharField(blank=True, help_text='Absolute path to combined figure_data.json file', max_length=500, null=True),
        ),
    ]
