# Generated by Django 5.2.3 on 2025-07-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='figure_data_object_key',
        ),
        migrations.AlterField(
            model_name='report',
            name='include_image',
            field=models.BooleanField(default=True, help_text='Whether to include figure data (images) during report generation'),
        ),
    ]
