# Generated by Django 5.2.3 on 2025-07-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_figure_data_object_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportimage',
            constraint=models.UniqueConstraint(
                fields=['figure_id', 'report'],
                name='unique_figure_per_report'
            ),
        ),
    ]
