# Generated by Django 5.2.3 on 2025-07-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_figure_data_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='prompt_type',
            field=models.CharField(choices=[('general', 'General'), ('financial', 'Financial'), ('paper', 'Paper')], default='general', max_length=50),
        ),
    ]
