# Generated by Django 5.2.3 on 2025-07-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_add_unique_constraint_figure_id_report'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportimage',
            name='unique_figure_per_report',
        ),
    ]
