# Generated by Django 5.2.3 on 2025-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_include_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_range',
            field=models.CharField(blank=True, choices=[('ALL', 'All Time'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=20, null=True),
        ),
    ]
