# Generated by Django 5.2.3 on 2025-07-10 14:06

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_include_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='main_report_file',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='reports/'),
        ),
    ]
