# Generated by Django 5.2.3 on 2025-07-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_main_report_file'),
        ('reports', '0009_alter_report_time_range'),
    ]

    operations = [
    ]
