# Generated by Django 5.2.3 on 2025-07-14 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0009_alter_source_options_alter_knowledgeitem_notes_and_more'),
        ('reports', '0012_remove_django_filefields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_created_a6aabf_idx',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['storage_uuid'], name='reports_rep_storage_d31fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['main_report_object_key'], name='reports_rep_main_re_462cd9_idx'),
        ),
    ]
