# Generated by Django 5.2.4 on 2025-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="publication",
            name="authors",
        ),
        migrations.AddField(
            model_name="publication",
            name="authors",
            field=models.ManyToManyField(
                related_name="publications", to="conferences.author"
            ),
        ),
    ]
