# Generated by Django 5.2.4 on 2025-07-11 18:59

import conferences.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_author_remove_publication_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="raw_file",
            field=models.FileField(
                blank=True,
                help_text="PDF file stored in MinIO",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=conferences.models.publication_file_path,
            ),
        ),
    ]
