# Generated by Django 5.2.4 on 2025-07-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0003_alter_publication_raw_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="authors",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.AddField(
            model_name="publication",
            name="authors",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
