# Generated by Django 5.2.3 on 2025-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_remove_publication_authors_delete_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='session',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
