services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS:    "http://0.0.0.0:2379"
      ALLOW_NONE_AUTHENTICATION:  "yes"
    ports:
      - "2379:2379"

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    ports:
      - "9000:9000"

  milvus-standalone:
    image: milvusdb/milvus:v2.2.16
    platform: linux/amd64
    command: ["/tini","--","milvus","run","standalone"]
    environment:
      ETCD_ENDPOINTS:   "etcd:2379"
      MINIO_ADDRESS:    "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"
      - "19121:19121"
