# Generated by Django 5.2.3 on 2025-07-15 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('url_parse', 'URL Parse'), ('url_parse_media', 'URL Parse with Media'), ('file_upload', 'File Upload')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='pending', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.CharField(help_text='Original filename or display name for the image', max_length=255)),
                ('image_caption', models.TextField(blank=True, help_text='Description or caption for the image')),
                ('image_id', models.PositiveIntegerField(help_text='Sequential ID within the knowledge base item (Figure 1, Figure 2, etc.)')),
                ('figure_name', models.CharField(blank=True, help_text="Display name like 'Figure 1', 'Figure 2', etc.", max_length=100)),
                ('storage_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for MinIO storage operations', unique=True)),
                ('minio_object_key', models.CharField(db_index=True, help_text='MinIO object key for the image file', max_length=255)),
                ('image_metadata', models.JSONField(default=dict, help_text='Image metadata including dimensions, format, size, etc.')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the image (image/png, image/jpeg, etc.)', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Image',
                'verbose_name_plural': 'Knowledge Base Images',
                'ordering': ['knowledge_base_item', 'image_id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title or identifier for this knowledge item', max_length=512)),
                ('content_type', models.CharField(choices=[('text', 'Text Content'), ('document', 'Document'), ('webpage', 'Webpage'), ('media', 'Media File')], default='text', max_length=50)),
                ('content', models.TextField(blank=True, help_text='Inline text content if not stored as file')),
                ('metadata', models.JSONField(blank=True, help_text='Source metadata, processing info, etc.', null=True)),
                ('source_hash', models.CharField(blank=True, db_index=True, help_text='Hash of original content to detect duplicates', max_length=64)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
                ('storage_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for MinIO storage operations', unique=True)),
                ('file_object_key', models.CharField(blank=True, db_index=True, help_text='MinIO object key for processed content file', max_length=255, null=True)),
                ('original_file_object_key', models.CharField(blank=True, db_index=True, help_text='MinIO object key for original file', max_length=255, null=True)),
                ('file_metadata', models.JSONField(default=dict, help_text='File metadata stored in database (replaces file system metadata)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this knowledge item in this notebook')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotebookChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(help_text='E.g. ocr, transcribe, pdf2md…', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('storage_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('result_file_object_key', models.CharField(blank=True, db_index=True, help_text='MinIO object key for generated result file', max_length=255, null=True)),
                ('result_file_metadata', models.JSONField(default=dict, help_text='Result file metadata (name, size, content_type, etc.)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('url', 'URL'), ('text', 'Pasted Text')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional display title or original filename/URL', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('needs_processing', models.BooleanField(default=False, help_text='Whether this source must go through a background processing job')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='URLProcessingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_md', models.TextField(blank=True, help_text='Markdown extracted from a webpage, if applicable')),
                ('storage_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('downloaded_file_object_key', models.CharField(blank=True, db_index=True, help_text='MinIO object key for downloaded media file', max_length=255, null=True)),
                ('file_metadata', models.JSONField(default=dict, help_text='Downloaded file metadata (name, size, content_type, etc.)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if crawl or download failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchJobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_data', models.JSONField(help_text='URL, filename, or other item-specific data')),
                ('upload_id', models.CharField(blank=True, help_text='Upload/processing ID for status tracking', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, help_text='Processing results', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notebooks.batchjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
