# Generated by Django 5.2.3 on 2025-06-21 03:31

import notebooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='result_file',
            field=models.FileField(blank=True, help_text='Generated .md or other output file', null=True, upload_to=notebooks.models.user_processing_results_path),
        ),
        migrations.AlterField(
            model_name='urlprocessingresult',
            name='downloaded_file',
            field=models.FileField(blank=True, help_text='Media file downloaded from the URL, if any', null=True, upload_to=notebooks.models.user_url_processing_path),
        ),
    ]
