# Generated by Django 5.2.3 on 2025-07-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseitem',
            name='user',
            field=models.ForeignKey(help_text='Owner of this knowledge item', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebaseimage',
            name='knowledge_base_item',
            field=models.ForeignKey(help_text='Knowledge base item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notebooks.knowledgebaseitem'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='knowledge_base_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_links', to='notebooks.knowledgebaseitem'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='batchjob',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='notebookchatmessage',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='source',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='notebooks.source'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Original source that created this knowledge item (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='notebooks.source'),
        ),
        migrations.AddField(
            model_name='urlprocessingresult',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_result', to='notebooks.source'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['user', '-created_at'], name='notebooks_k_user_id_d865ea_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['user', 'source_hash'], name='notebooks_k_user_id_424da8_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['user', 'content_type'], name='notebooks_k_user_id_899dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['storage_uuid'], name='notebooks_k_storage_be410c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['file_object_key'], name='notebooks_k_file_ob_b76e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['original_file_object_key'], name='notebooks_k_origina_939f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['knowledge_base_item', 'image_id'], name='notebooks_k_knowled_04b9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['minio_object_key'], name='notebooks_k_minio_o_bcbe25_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['storage_uuid'], name='notebooks_k_storage_9f2364_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebaseimage',
            unique_together={('knowledge_base_item', 'image_id')},
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['notebook', '-added_at'], name='notebooks_k_noteboo_c452a0_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['knowledge_base_item'], name='notebooks_k_knowled_2d8ad9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgeitem',
            unique_together={('notebook', 'knowledge_base_item')},
        ),
    ]
