# Generated by Django 5.2.4 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgebaseimage',
            new_name='notebooks_k_knowled_01b34a_idx',
            old_name='notebooks_kbi_kb_created_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaseimage',
            new_name='notebooks_k_minio_o_bcbe25_idx',
            old_name='notebooks_kbi_minio_key_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaseitem',
            new_name='notebooks_k_noteboo_a2cd57_idx',
            old_name='notebooks_kb_notebook_created_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaseitem',
            new_name='notebooks_k_noteboo_fd687d_idx',
            old_name='notebooks_kb_notebook_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaseitem',
            new_name='notebooks_k_noteboo_74218b_idx',
            old_name='notebooks_kb_notebook_type_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaseitem',
            new_name='notebooks_k_file_ob_b76e2e_idx',
            old_name='notebooks_kb_file_key_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaseitem',
            new_name='notebooks_k_origina_939f6d_idx',
            old_name='notebooks_kb_orig_file_key_idx',
        ),
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='processing_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='processing', help_text='Processing status of this knowledge base item', max_length=20),
        ),
    ]
