# Generated by Django 5.2.3 on 2025-07-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebaseimage',
            options={'ordering': ['knowledge_base_item', 'figure_id'], 'verbose_name': 'Knowledge Base Image', 'verbose_name_plural': 'Knowledge Base Images'},
        ),
        migrations.RemoveIndex(
            model_name='knowledgebaseimage',
            name='notebooks_k_knowled_04b9a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgebaseimage',
            name='notebooks_k_storage_9f2364_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgebaseitem',
            name='notebooks_k_storage_be410c_idx',
        ),
        migrations.RenameField(
            model_name='knowledgebaseimage',
            old_name='image_id',
            new_name='figure_id',
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebaseimage',
            unique_together={('knowledge_base_item', 'figure_id')},
        ),
        migrations.RemoveField(
            model_name='knowledgebaseitem',
            name='storage_uuid',
        ),
        migrations.RemoveField(
            model_name='processingjob',
            name='storage_uuid',
        ),
        migrations.RemoveField(
            model_name='urlprocessingresult',
            name='storage_uuid',
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['knowledge_base_item', 'figure_id'], name='notebooks_k_knowled_37d96e_idx'),
        ),
        migrations.RemoveField(
            model_name='knowledgebaseimage',
            name='figure_name',
        ),
        migrations.RemoveField(
            model_name='knowledgebaseimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='knowledgebaseimage',
            name='storage_uuid',
        ),
    ]
