# Generated by Django 5.2.4 on 2025-08-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='file_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='File metadata stored in database'),
        ),
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization and search'),
        ),
    ]
