# Generated by Django 5.2.3 on 2025-06-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_batchjob_batchjobitem'),
        ('notebooks', '0003_notebookchatmessage'),
    ]

    operations = [
    ]
