# Generated by Django 5.2.3 on 2025-07-10 14:06

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_merge_20250628_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='file',
            field=models.FileField(blank=True, help_text="Processed content file in the user's knowledge base", null=True, storage=storages.backends.s3.S3Storage(), upload_to='knowledge_base/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='original_file',
            field=models.FileField(blank=True, help_text="Original binary file (PDF, audio, video, etc.) in the user's knowledge base", null=True, storage=storages.backends.s3.S3Storage(), upload_to='knowledge_base/'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='result_file',
            field=models.FileField(blank=True, help_text='Generated .md or other output file', null=True, storage=storages.backends.s3.S3Storage(), upload_to='knowledge_base/'),
        ),
        migrations.AlterField(
            model_name='urlprocessingresult',
            name='downloaded_file',
            field=models.FileField(blank=True, help_text='Media file downloaded from the URL, if any', null=True, storage=storages.backends.s3.S3Storage(), upload_to='knowledge_base/'),
        ),
    ]
