# Generated by Django 5.2.3 on 2025-07-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_add_minio_fields'),
        ('notebooks', '0005_alter_knowledgebaseitem_file_and_more'),
    ]

    operations = [
    ]
