# Generated by Django 5.2.3 on 2025-07-14 13:51

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0006_merge_20250714_1351'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='file_metadata',
            field=models.JSONField(default=dict, help_text='File metadata stored in database (replaces file system metadata)'),
        ),
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='storage_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for MinIO storage operations', unique=True),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['storage_uuid'], name='notebooks_k_storage_be410c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['file_object_key'], name='notebooks_k_file_ob_b76e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseitem',
            index=models.Index(fields=['original_file_object_key'], name='notebooks_k_origina_939f6d_idx'),
        ),
    ]
