# Generated by Django 5.2.4 on 2025-07-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0007_urlprocessingresult_original_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlprocessingresult',
            name='original_url',
        ),
    ]
