# Generated by Django 5.2.3 on 2025-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0008_remove_django_filefields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='notes',
            field=models.TextField(blank=True, help_text='User notes about this knowledge item in this notebook'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='result_file_metadata',
            field=models.JSONField(default=dict, help_text='Result file metadata (name, size, content_type, etc.)'),
        ),
        migrations.AlterField(
            model_name='urlprocessingresult',
            name='file_metadata',
            field=models.JSONField(default=dict, help_text='Downloaded file metadata (name, size, content_type, etc.)'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['knowledge_base_item'], name='notebooks_k_knowled_2d8ad9_idx'),
        ),
    ]
