# Generated by Django 5.2.3 on 2025-07-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0008_remove_urlprocessingresult_original_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLProcessingResult',
        ),
    ]
