# Generated by Django 5.2.3 on 2025-06-16 14:18

import django.db.models.deletion
import notebooks.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotebookSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('publication', 'Publication'), ('event', 'Event')], max_length=50)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='notebooks.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=notebooks.models.upload_to_notebook)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', help_text='Track parsing (validation → content checks → completed)', max_length=20)),
                ('validation_result', models.JSONField(blank=True, default=dict, help_text='Output of FileValidator.validate_file()')),
                ('processing_result', models.JSONField(blank=True, default=dict, help_text='Output of UploadProcessor.process_upload()')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['upload_file_id'], name='notebooks_u_upload__02fabf_idx'), models.Index(fields=['status'], name='notebooks_u_status_e4a746_idx')],
            },
        ),
    ]
