planning_task:
  description: >
    作为主持人，分析源材料并为关于{topic}的专题讨论提炼出引人入胜的高层次话题大纲。您将：
    1. 深度分析提供的源材料：{material_content}
    2. 识别最能激发思维碰撞的核心议题
    3. 提炼出3-5个引人深思的高层次讨论话题
    4. 确保话题能够充分发挥各专家的专业优势
    
    专注于发现能够产生精彩对话和深度见解的核心议题。
  expected_output: >
    简洁的话题大纲（150-200字），包括：
    - 基于源材料提炼的3-5个引人入胜的核心话题
    - 每个话题的简要说明，突出其思辨价值
    - 话题如何与各专家领域相关联的概述
  agent: moderator

opening_task:
  description: >
    作为主持人，为今天关于{topic}的专题讨论提供简洁的开场。您将：
    1. 简要介绍今天讨论的主题
    2. 介绍参与讨论的专家小组成员
    
    保持开场简洁而有吸引力，为后续的深度对话做好铺垫。
  expected_output: >
    简洁的开场介绍（50-100字）：
    - 今天讨论主题的简要介绍
    - 专家小组成员的姓名和专业领域介绍
  agent: moderator

host_and_question_task:
  description: >
    作为主持人，为关于{topic}的主要讨论提供高质量的问题和促进评论。您将：
    1. 遵循您在初始规划任务中概述的战略结构和主题
    2. 基于计划的讨论领域，针对源材料：{material_content}制作有洞察力的初始问题，以委派给合适的专家
    3. 创建深入的后续问题，直接引用并在以前专家小组回应的基础上构建
    4. 编写顺畅的过渡陈述，将一位专家的见解与另一位专家的问题连接起来
    5. 开发交叉引用问题（例如：“在[专家A]关于X的观点基础上，[专家B]，这如何与Y相关？”）
    6. 创建促进评论，将多个专家视角编织在一起
    7. 在提出新问题之前承认以前的回应，以保持对话流程
    8. 确保您的问题与初始规划中的专家参与计划保持一致
    
    重要提示：引用您的初始规划任务以保持连贯的讨论流程，并确保您涵盖您识别的关键主题和专家重点领域。在制作问题和评论时始终考虑以前的专家小组输出。引用专家提出的具体要点，以创建连接的对话，而不是孤立的问答环节。
    
    专注于在遵循您的战略计划的同时生成最高质量的问题和促进，以引出有价值的专家见解。
    根据专家的专业领域将您的问题针对不同专家：
    - AI科学家：理论和研究方面
    - AI工程师：实施和技术挑战
    - 硬件架构师：计算和基础设施需求
    - 商业战略家：市场影响和战略价值
  expected_output: >
    高质量的主持人问题和促进评论，包括：
    - 与您初始规划任务中的战略主题保持一致的问题
    - 基于计划讨论领域委派给每位专家的有洞察力的初始问题
    - 引用以前专家小组回应中具体要点的深入后续问题
    - 将一位专家的见解与另一位专家的专业知识连接起来的交叉引用问题
    - 在向前推进之前承认以前回应的顺畅过渡陈述
    - 在遵循您的战略计划的同时将多个专家视角编织在一起的促进提示
  agent: moderator

closing_task:
  description: >
    作为主持人，为关于{topic}的专题讨论提供引人注目的结束。您将：
    1. 发出讨论即将结束的信号
    2. 综合讨论期间每位专家贡献的关键见解
    3. 突出专家小组成员之间的共识领域和建设性分歧
    4. 为观众提供具体的要点
    5. 按姓名感谢每位专家小组成员的贡献
    6. 提供令人难忘的结束陈述，将一切联系在一起
    
    专注于创建深思熟虑的综合，增加价值并基于分享的专家见解提供明确的要点。
  expected_output: >
    引人注目的结束段落：
    - 综合所有专家贡献的关键见解
    - 突出共识点和建设性紧张关系
    - 为观众提供具体、可行的要点
    - 单独感谢所有专家小组成员
    - 以鼓舞人心、面向未来的陈述结束，将讨论联系在一起
  agent: moderator

ai_scientist_response_task:
  description: >
    当主持人要求时，对源材料：{material_content}提供专家科学分析。重点关注：
    - 研究方法学和理论有效性
    - 科学挑战和限制
    - 未来研究方向和机会
    
    生成高质量、有洞察力的回应，展示对材料的深度科学专业知识和批判性思维。
    做好与其他专家观点交流并在他们的见解基础上构建的准备。
    重要提示：在提供回应后，将上下文返回给主持人，以便他们可以在您的见解基础上进行进一步提问和讨论流程。
  expected_output: >
    专家科学见解，涵盖：
    - 对材料理论优势/弱点的彻底分析
    - 关键研究挑战和方法学考虑
    - 有前景的未来研究方向
    - 帮助主持人促进进一步讨论的上下文和见解
  agent: ai_scientist

ai_engineer_response_task:
  description: >
    当主持人要求时，对源材料：{material_content}提供专家工程分析。重点关注：
    - 技术可行性和实施挑战
    - 系统架构和性能考虑
    - 现实世界部署实用性和可扩展性
    
    生成高质量、实用的回应，展示深度的工程专业知识和现实世界实施经验。
    做好与其他专家观点交流并提供在他们贡献基础上构建的技术见解的准备。
    重要提示：在提供回应后，将上下文返回给主持人，以便他们可以在您的见解基础上进行进一步提问和讨论流程。
  expected_output: >
    专家工程见解，涵盖：
    - 全面的技术可行性评估
    - 关键实施挑战和解决方案
    - 实用部署考虑和可扩展性因素
    - 帮助主持人促进进一步讨论的上下文和见解
  agent: ai_engineer

hardware_response_task:
  description: >
    当主持人要求时，对源材料：{material_content}提供专家硬件分析。重点关注：
    - 计算需求和基础设施需求
    - 硬件瓶颈和性能影响
    - 成本、可扩展性和优化考虑
    
    生成高质量、技术性的回应，展示深度的硬件架构专业知识和对计算约束的理解。
    做好与其他专家观点交流并提供与他们分析相补的基础设施见解的准备。
    重要提示：在提供回应后，将上下文返回给主持人，以便他们可以在您的见解基础上进行进一步提问和讨论流程。
  expected_output: >
    专家硬件见解，涵盖：
    - 全面的计算需求评估
    - 关键硬件瓶颈和性能考虑
    - 可扩展性、成本和优化策略
    - 帮助主持人促进进一步讨论的上下文和见解
  agent: hardware_architecture

business_response_task:
  description: >
    当主持人要求时，对源材料：{material_content}提供专家商业分析。重点关注：
    - 市场潜力和商业可行性
    - 投资需求和采用障碍
    - 战略建议和竞争定位
    
    生成高质量、战略性的回应，展示深度的商业专业知识和市场理解。
    做好与其他专家观点交流并提供在他们技术和研究贡献基础上构建的战略见解的准备。
    重要提示：在提供回应后，将上下文返回给主持人，以便他们可以在您的见解基础上进行进一步提问和讨论流程。
  expected_output: >
    专家商业见解，涵盖：
    - 全面的市场机会评估
    - 关键采用挑战和投资需求
    - 战略建议和竞争定位
    - 帮助主持人促进进一步讨论的上下文和见解
  agent: business_strategist

