# Generated by Django 5.2.3 on 2025-06-25 03:10

import django.db.models.deletion
import podcast.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(default='Generated Podcast', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.TextField(default='Job queued for processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=podcast.models.user_podcast_audio_path)),
                ('conversation_text', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_file_ids', models.JSONField(default=list)),
                ('source_metadata', models.JSONField(default=dict)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('notebooks', models.ForeignKey(help_text='Associated notebook (required)', on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='notebooks.notebook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='podcast_pod_status_f6dc5d_idx'), models.Index(fields=['user', 'created_at'], name='podcast_pod_user_id_c3bdfe_idx'), models.Index(fields=['notebooks', 'created_at'], name='podcast_pod_noteboo_e03c3d_idx')],
            },
        ),
    ]
