# Generated by Django 5.2.3 - Clean initial migration for optimized Podcast model

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(default='Generated Podcast', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.TextField(default='Job queued for processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_object_key', models.CharField(blank=True, db_index=True, help_text='MinIO object key for generated audio file', max_length=255, null=True)),
                ('file_metadata', models.JSONField(default=dict, help_text='Audio file metadata (filename, size, duration, etc.)')),
                ('conversation_text', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_file_ids', models.JSONField(default=list)),
                ('source_metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notebook', models.ForeignKey(help_text='Associated notebook (required)', on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['status'], name='podcast_pod_status_f6dc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['user', 'created_at'], name='podcast_pod_user_id_c3bdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['audio_object_key'], name='podcast_pod_audio_o_b023f6_idx'),
        ),
    ]