# Generated by Django 5.2.3 on 2025-07-15 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(default='Generated Podcast', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.TextField(default='Job queued for processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('audio_object_key', models.CharField(blank=True, db_index=True, help_text='MinIO object key for generated audio file', max_length=255, null=True)),
                ('file_metadata', models.JSONField(default=dict, help_text='Audio file metadata (filename, size, duration, etc.)')),
                ('conversation_text', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_file_ids', models.JSONField(default=list)),
                ('source_metadata', models.JSONField(default=dict)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('notebooks', models.ForeignKey(help_text='Associated notebook (required)', on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
