# Generated by Django 5.2.3 on 2025-07-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcast', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='podcastjob',
            index=models.Index(fields=['status'], name='podcast_pod_status_f6dc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastjob',
            index=models.Index(fields=['user', 'created_at'], name='podcast_pod_user_id_c3bdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastjob',
            index=models.Index(fields=['storage_uuid'], name='podcast_pod_storage_a0210f_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastjob',
            index=models.Index(fields=['audio_object_key'], name='podcast_pod_audio_o_b023f6_idx'),
        ),
    ]
