# Generated by Django 5.2.4 on 2025-07-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='podcast',
            new_name='podcast_pod_status_5de595_idx',
            old_name='podcast_pod_status_f6dc5d_idx',
        ),
        migrations.RenameIndex(
            model_name='podcast',
            new_name='podcast_pod_user_id_ec4ead_idx',
            old_name='podcast_pod_user_id_c3bdfe_idx',
        ),
        migrations.RenameIndex(
            model_name='podcast',
            new_name='podcast_pod_audio_o_359513_idx',
            old_name='podcast_pod_audio_o_b023f6_idx',
        ),
        migrations.AddField(
            model_name='podcast',
            name='custom_instruction',
            field=models.TextField(blank=True, help_text='Custom discussion instruction', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='result_data',
            field=models.JSONField(blank=True, default=dict, help_text='Generated podcast result data'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='status_message',
            field=models.TextField(default='Job queued for processing'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
    ]
