# Generated by Django 5.2.3 on 2025-07-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='podcastjob',
            name='podcast_pod_storage_a0210f_idx',
        ),
        migrations.RemoveField(
            model_name='podcastjob',
            name='storage_uuid',
        ),
    ]
