# Generated by Django 5.2.3 on 2025-07-14 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0009_alter_source_options_alter_knowledgeitem_notes_and_more'),
        ('podcast', '0003_remove_django_filefields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='podcastjob',
            name='podcast_pod_noteboo_e03c3d_idx',
        ),
        migrations.AddIndex(
            model_name='podcastjob',
            index=models.Index(fields=['storage_uuid'], name='podcast_pod_storage_a0210f_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastjob',
            index=models.Index(fields=['audio_object_key'], name='podcast_pod_audio_o_b023f6_idx'),
        ),
    ]
