# Generated by Django 5.2.3 on 2025-06-24 20:38

import django.db.models.deletion
import podcast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
        ('podcast', '0003_podcastjob_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastjob',
            name='notebooks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='notebooks.notebook'),
        ),
        migrations.AlterField(
            model_name='podcastjob',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=podcast.models.user_podcast_audio_path),
        ),
    ]
