# Generated by Django 5.2.3 on 2025-07-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_alter_knowledgebaseimage_options_and_more'),
    ]

    operations = [
        # First remove old index and constraints
        migrations.RemoveIndex(
            model_name='knowledgebaseimage',
            name='notebooks_k_knowled_37d96e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebaseimage',
            unique_together=set(),
        ),
        # Add new field
        migrations.AddField(
            model_name='knowledgebaseimage',
            name='figure_name',
            field=models.CharField(default='Figure 1', help_text="Figure name like 'Figure 1', 'Figure 2', extracted from PDF or auto-generated", max_length=100),
        ),
        # Remove old field
        migrations.RemoveField(
            model_name='knowledgebaseimage',
            name='figure_id',
        ),
        # Now add new constraints and ordering
        migrations.AlterModelOptions(
            name='knowledgebaseimage',
            options={'ordering': ['knowledge_base_item', 'figure_name'], 'verbose_name': 'Knowledge Base Image', 'verbose_name_plural': 'Knowledge Base Images'},
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebaseimage',
            unique_together={('knowledge_base_item', 'figure_name')},
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['knowledge_base_item', 'figure_name'], name='notebooks_k_knowled_8c783a_idx'),
        ),
    ]
