# Generated by Django 5.2.3 on 2025-07-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_alter_knowledgebaseimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebaseimage',
            options={'ordering': ['knowledge_base_item', 'created_at'], 'verbose_name': 'Knowledge Base Image', 'verbose_name_plural': 'Knowledge Base Images'},
        ),
        migrations.RemoveIndex(
            model_name='knowledgebaseimage',
            name='notebooks_k_knowled_8c783a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebaseimage',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseimage',
            index=models.Index(fields=['knowledge_base_item', 'created_at'], name='notebooks_k_knowled_01b34a_idx'),
        ),
        migrations.RemoveField(
            model_name='knowledgebaseimage',
            name='figure_name',
        ),
    ]
