# Generated by Django 5.2.3 on 2025-07-17 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_alter_knowledgebaseimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseimage',
            name='figure_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique figure identifier, different from primary key'),
        ),
    ]
