# Generated by Django 5.2.4 on 2025-07-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0006_knowledgebaseimage_figure_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlprocessingresult',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
