# Generated by Django 5.2.3 on 2025-07-24 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0009_drop_urlprocessingresult_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='needs_processing',
        ),
        migrations.RemoveField(
            model_name='source',
            name='processing_status',
        ),
        migrations.AddField(
            model_name='knowledgebaseitem',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('error', 'Error')], default='pending', help_text='Processing status of this knowledge base item', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgebaseitem',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Source that created this knowledge base item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_base_items', to='notebooks.source'),
        ),
    ]
