# Generated by Django 5.2.3 on 2025-06-17 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('transcript_content', models.TextField(blank=True)),
                ('paper_content', models.TextField(blank=True)),
                ('article_title', models.CharField(default='Research Report', max_length=255)),
                ('model_provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=50)),
                ('retriever', models.CharField(choices=[('tavily', 'Tavily')], default='tavily', max_length=50)),
                ('temperature', models.FloatField(default=0.2)),
                ('top_p', models.FloatField(default=0.4)),
                ('max_conv_turn', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='notebook.notebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
